segmentation:
  seg_suffix: "####"
  mode: "unistream"
  unistream:
    first_max_accu_time: 0.2
    max_accu_time: 1.0
    first_max_buffer_size: 20
    max_buffer_size: 50
    max_waiting_time: 2.0
    max_stream_time: 60.0
    first_min_seg_size: 20
    min_seg_size: 50
    max_seg_size: 70
    loose_steps: 4
    loose_size: 10
    fade_in_out_time: 0.2
    seconds_per_word: 0.3
  bistream:
    max_waiting_time: 2.0
    max_stream_time: 50.0
    first_min_seg_size: 50
    min_seg_size: 50

tts:
  do_removing_silence: False
  first_left_retention_seconds: 0.7
  left_retention_seconds: 1.0
  right_retention_seconds: 1.0
